// <auto-generated />
namespace Crazy2018_Sys_DBHelper.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _120350 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_120350));
        
        string IMigrationMetadata.Id
        {
            get { return "202010220832100_120350"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
