//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class bankcardentities
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string BankCardID { get; set; }
        public Nullable<int> CardType { get; set; }
        public string CardName { get; set; }
        public string BankAddress { get; set; }
        public string Location { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public Nullable<System.DateTime> CreatTime { get; set; }
        public Nullable<int> UserEntity_ID { get; set; }
    }
}
