//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class gameuser
    {
        public int UserId { get; set; }
        public string NickName { get; set; }
        public string PassportId { get; set; }
        public string RetailId { get; set; }
        public string HeadIcon { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string Email { get; set; }
        public string MobilePhoneNum { get; set; }
        public string PassportPwd { get; set; }
        public Nullable<short> UserLevel { get; set; }
        public Nullable<int> ExpNum { get; set; }
        public Nullable<int> LoginNum { get; set; }
        public Nullable<System.DateTime> FinalTime { get; set; }
        public string RecommendedId { get; set; }
        public Nullable<sbyte> Vip { get; set; }
        public Nullable<int> UserStatus { get; set; }
        public Nullable<int> MoneyScore { get; set; }
        public string Birthday { get; set; }
        public Nullable<System.DateTime> RegisterTime { get; set; }
        public Nullable<sbyte> MobileType { get; set; }
        public string IDCards { get; set; }
        public string WeixinCode { get; set; }
        public Nullable<System.DateTime> PassportPwdTime { get; set; }
        public Nullable<int> RedEnvCount { get; set; }
        public Nullable<int> RedCount { get; set; }
        public Nullable<int> ClRedCount { get; set; }
        public string alipayName { get; set; }
        public string alipayNum { get; set; }
        public string BankUn { get; set; }
        public string BankNum { get; set; }
        public string BankName { get; set; }
        public string bPhone { get; set; }
        public string aPhone { get; set; }
        public Nullable<int> JlRedCount { get; set; }
        public string BankProvince { get; set; }
        public string BankCity { get; set; }
    }
}
