//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class rechargechannels
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string IP { get; set; }
        public string MachineCode { get; set; }
        public Nullable<int> MachineType { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ChannelName { get; set; }
        public string ChannelCode { get; set; }
        public string payurl { get; set; }
        public string dec { get; set; }
        public string minmoney { get; set; }
        public string paytype { get; set; }
        public Nullable<bool> isenable { get; set; }
        public string payname { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public Nullable<System.DateTime> CreatTime { get; set; }
        public string serviceList { get; set; }
    }
}
