//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class smsrecord
    {
        public string ID { get; set; }
        public Nullable<int> SmsType { get; set; }
        public Nullable<int> UserId { get; set; }
        public string MobilePhoneNum { get; set; }
        public string KeyNum { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string DeviceID { get; set; }
        public string IP { get; set; }
    }
}
