//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class snscenterwhirl_snsuserinfo
    {
        public int UserId { get; set; }
        public string PassportID { get; set; }
        public string PassportPwd { get; set; }
        public string DeviceID { get; set; }
        public Nullable<short> RegType { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
        public string RetailID { get; set; }
        public string RetailUser { get; set; }
        public string Mobile { get; set; }
        public string Mail { get; set; }
        public Nullable<int> PwdType { get; set; }
        public string RealName { get; set; }
        public string IDCards { get; set; }
        public string ActiveCode { get; set; }
        public Nullable<System.DateTime> SendActiveDate { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
        public int SID { get; set; }
        public string WeixinCode { get; set; }
    }
}
