//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbemail
    {
        public string TradeNo { get; set; }
        public Nullable<int> FromUserId { get; set; }
        public Nullable<int> ToUserId { get; set; }
        public Nullable<int> MailType { get; set; }
        public string Content { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Attach { get; set; }
        public Nullable<int> CState { get; set; }
        public Nullable<bool> IsLook { get; set; }
        public Nullable<int> EmailType { get; set; }
        public string Title { get; set; }
    }
}
