//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tclubtaxlog
    {
        public int Id { get; set; }
        public Nullable<int> gameid { get; set; }
        public Nullable<int> clubid { get; set; }
        public Nullable<int> allid { get; set; }
        public Nullable<long> gold { get; set; }
        public Nullable<long> totalgold { get; set; }
        public string tnum { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
