//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcluballiance
    {
        public long idx { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string childs { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<int> limitcount { get; set; }
        public Nullable<bool> search { get; set; }
        public Nullable<bool> manager { get; set; }
        public Nullable<long> gold { get; set; }
        public Nullable<long> diam { get; set; }
        public string applyclubidx { get; set; }
        public Nullable<int> lv { get; set; }
        public Nullable<bool> closeapply { get; set; }
        public Nullable<int> clubid { get; set; }
        public Nullable<bool> IsSupper { get; set; }
        public Nullable<long> jackpot { get; set; }
        public Nullable<long> inspot { get; set; }
    }
}
