//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcollectlog
    {
        public string Id { get; set; }
        public string sceneInfo { get; set; }
        public string sceneUserInfo { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> tnum { get; set; }
        public string infoId { get; set; }
        public Nullable<int> baserate { get; set; }
        public Nullable<int> gNum { get; set; }
        public Nullable<int> totalnum { get; set; }
        public Nullable<int> WinUserId { get; set; }
        public Nullable<long> WinGold { get; set; }
        public Nullable<int> seeNum { get; set; }
        public Nullable<int> NoGiveupNum { get; set; }
        public string maxPoker { get; set; }
        public string OwnSpair { get; set; }
        public Nullable<long> OwnWin { get; set; }
        public Nullable<int> preG { get; set; }
        public string PlayerList { get; set; }
        public Nullable<int> showCard { get; set; }
    }
}
