//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcommodity
    {
        public int id { get; set; }
        public string name { get; set; }
        public string introduce { get; set; }
        public Nullable<double> exchangeValue { get; set; }
        public Nullable<int> commodityType { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> isEnable { get; set; }
        public Nullable<float> commodityvValue { get; set; }
        public string Discount { get; set; }
        public Nullable<int> ClubCount { get; set; }
        public Nullable<int> TableCount { get; set; }
    }
}
