//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class temtuseragent
    {
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<long> Commission { get; set; }
        public int Id { get; set; }
        public Nullable<long> UserProfit { get; set; }
        public Nullable<int> pos1Count { get; set; }
        public Nullable<int> pos2Count { get; set; }
        public Nullable<int> pos5Count { get; set; }
        public Nullable<int> pos10Count { get; set; }
        public Nullable<int> pos20Count { get; set; }
        public Nullable<int> pos50Count { get; set; }
        public Nullable<int> GameId { get; set; }
    }
}
