//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class texchangelog
    {
        public string Id { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> isHandle { get; set; }
        public string oddNumbers { get; set; }
        public string expressNumbers { get; set; }
        public string name { get; set; }
        public Nullable<int> commodityType { get; set; }
        public string QRCodeUrl { get; set; }
        public Nullable<int> exchangeCount { get; set; }
    }
}
