//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tgameinfo
    {
        public int id { get; set; }
        public string name { get; set; }
        public string modifyUser { get; set; }
        public Nullable<System.DateTime> modifyTime { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> isHot { get; set; }
        public string desc { get; set; }
        public Nullable<bool> isopen { get; set; }
        public Nullable<int> type { get; set; }
        public string gameurl { get; set; }
        public Nullable<int> port { get; set; }
        public string gameRule { get; set; }
        public string icon { get; set; }
        public string gameIntroduce { get; set; }
        public Nullable<bool> isEnable { get; set; }
        public string isEnableDesc { get; set; }
        public Nullable<bool> deleteState { get; set; }
        public Nullable<int> gameType { get; set; }
        public string gameIp { get; set; }
        public Nullable<int> gamePort { get; set; }
        public Nullable<int> platType { get; set; }
        public Nullable<int> jdbType { get; set; }
        public Nullable<int> IsRun { get; set; }
    }
}
