//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tgamelevelinfo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Baserate { get; set; }
        public Nullable<int> gameid { get; set; }
        public Nullable<int> C_min { get; set; }
        public Nullable<int> C_max { get; set; }
        public Nullable<int> onlineCount { get; set; }
        public Nullable<int> openTableCount { get; set; }
        public Nullable<int> gametype { get; set; }
        public string gametypeDesc { get; set; }
        public Nullable<int> isEnable { get; set; }
        public string isEnableDesc { get; set; }
        public Nullable<int> deleteState { get; set; }
        public string modifyUser { get; set; }
        public Nullable<System.DateTime> modifyTime { get; set; }
        public string Description { get; set; }
    }
}
