//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tjackpotstock
    {
        public int Id { get; set; }
        public Nullable<int> gameid { get; set; }
        public Nullable<int> isEnable { get; set; }
        public string isEnableDesc { get; set; }
        public Nullable<int> deleteState { get; set; }
        public string modifyUser { get; set; }
        public Nullable<System.DateTime> modifyTime { get; set; }
        public string Description { get; set; }
        public Nullable<int> pump { get; set; }
        public Nullable<int> waterproof { get; set; }
        public Nullable<long> historygambleall { get; set; }
        public Nullable<long> income { get; set; }
        public Nullable<long> rax { get; set; }
        public Nullable<int> handsel { get; set; }
        public Nullable<long> stock { get; set; }
        public Nullable<int> levelid { get; set; }
        public Nullable<long> outcomes { get; set; }
        public Nullable<long> balanceScore { get; set; }
    }
}
