//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tjdbwagerlog
    {
        public string transferId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> gType { get; set; }
        public Nullable<int> mType { get; set; }
        public Nullable<double> bet { get; set; }
        public Nullable<double> win { get; set; }
        public Nullable<double> netWin { get; set; }
        public string ipAddress { get; set; }
        public Nullable<System.DateTime> gameDate { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> IsSuccess { get; set; }
    }
}
