//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tonlineinfo
    {
        public long id { get; set; }
        public Nullable<int> GameId { get; set; }
        public Nullable<int> GameType { get; set; }
        public Nullable<int> OnlineCount { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> GameModel { get; set; }
        public Nullable<int> rCount { get; set; }
    }
}
