//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class troomlist
    {
        public long Idx { get; set; }
        public string Name { get; set; }
        public string RoomDescribe { get; set; }
        public string Gamename { get; set; }
        public string GametypeId { get; set; }
        public string IsEnable { get; set; }
        public string Pi { get; set; }
        public string PeopleNum { get; set; }
        public string Autostart { get; set; }
        public string Duration { get; set; }
        public string MinBring { get; set; }
        public string IsZm { get; set; }
        public string IsQm { get; set; }
        public string IsDw { get; set; }
        public string IsQcqm { get; set; }
        public string Createuser { get; set; }
        public string Createtime { get; set; }
        public string modifyUser { get; set; }
        public string modifyTime { get; set; }
        public string States { get; set; }
    }
}
