//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ttableuserlog
    {
        public long Idx { get; set; }
        public Nullable<long> TableLogIdx { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> C_pos { get; set; }
        public Nullable<decimal> gold { get; set; }
        public string C_cardList { get; set; }
        public Nullable<int> gameid { get; set; }
        public Nullable<bool> C_isover { get; set; }
        public Nullable<int> C_isWatch { get; set; }
        public Nullable<bool> C_win { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> trendIdx { get; set; }
        public string mystake { get; set; }
        public Nullable<long> Bet { get; set; }
        public string TaxString { get; set; }
        public Nullable<int> levelid { get; set; }
        public Nullable<int> basegamle { get; set; }
    }
}
