//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ttablegainlog
    {
        public long Idx { get; set; }
        public string MatchCode { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> gameid { get; set; }
        public Nullable<bool> C_isover { get; set; }
        public Nullable<int> gcount { get; set; }
        public Nullable<int> jackpot { get; set; }
        public string ChildAgents { get; set; }
    }
}
