//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ttablelist
    {
        public int tableNum { get; set; }
        public Nullable<int> gameid { get; set; }
        public Nullable<int> levelid { get; set; }
        public string createTime { get; set; }
        public Nullable<int> maxCount { get; set; }
        public Nullable<int> curCount { get; set; }
        public Nullable<int> ownerId { get; set; }
        public Nullable<int> tableStatus { get; set; }
        public Nullable<int> tableid { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> firstinto { get; set; }
        public Nullable<int> baserate { get; set; }
        public string password { get; set; }
        public Nullable<int> minPlayerCount { get; set; }
        public string para { get; set; }
        public string data { get; set; }
        public string mjpara { get; set; }
        public Nullable<int> ClubIdx { get; set; }
        public string tname { get; set; }
        public Nullable<int> manNum { get; set; }
        public Nullable<bool> cinto { get; set; }
        public Nullable<int> allId { get; set; }
    }
}
