//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ttaxlog
    {
        public long Idx { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<long> BeforCoin { get; set; }
        public Nullable<double> ActionCoin { get; set; }
        public Nullable<long> AfterCoin { get; set; }
        public Nullable<int> ActionType { get; set; }
        public Nullable<int> SourceGameID { get; set; }
        public Nullable<int> SourceUserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> TableUserLogId { get; set; }
        public Nullable<bool> IsHandel { get; set; }
        public Nullable<int> C_lv { get; set; }
        public Nullable<int> SourceRoomID { get; set; }
    }
}
