//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tuservipfreecount
    {
        public string id { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> vipid { get; set; }
        public Nullable<int> freecount { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
    }
}
