//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tuserjackpot
    {
        public int UserId { get; set; }
        public string C_jackpot { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public Nullable<long> watergoldadd { get; set; }
        public Nullable<long> watergoldreduce { get; set; }
        public Nullable<long> GoldHistoryCommission { get; set; }
        public Nullable<long> HistoryGold { get; set; }
        public Nullable<long> AllGoldBack { get; set; }
        public Nullable<long> AllGoldAdd { get; set; }
        public string C_potRange { get; set; }
    }
}
