//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tuseragent2020
    {
        public int UserID { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<int> PartnerID { get; set; }
        public Nullable<int> CEOID { get; set; }
        public Nullable<long> GoldCHistory { get; set; }
        public Nullable<double> GoldC { get; set; }
        public Nullable<long> GoldCH_P { get; set; }
        public Nullable<long> GoldCH_G { get; set; }
        public Nullable<System.DateTime> lastdealtime { get; set; }
        public string ChildAgents { get; set; }
        public string rates { get; set; }
        public string JackpotRate { get; set; }
        public Nullable<int> GoldCH_P_R { get; set; }
        public Nullable<int> GoldCH_G_R { get; set; }
        public Nullable<double> GoldC_pot { get; set; }
        public Nullable<double> GoldCH_pot { get; set; }
        public Nullable<double> GoldCH { get; set; }
        public string PotRates { get; set; }
    }
}
