//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tuser
    {
        public int UserID { get; set; }
        public string wechatName { get; set; }
        public Nullable<long> Gold { get; set; }
        public Nullable<decimal> GoldA { get; set; }
        public string LastLotinTime1 { get; set; }
        public string LastLotinTime2 { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
        public string IP { get; set; }
        public string Desc { get; set; }
        public Nullable<int> isRobot { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<long> diamond { get; set; }
        public Nullable<int> isagent { get; set; }
        public string wechatHeadIcon { get; set; }
        public Nullable<int> Sex { get; set; }
        public decimal TotalMoney { get; set; }
        public Nullable<long> totaldiamond { get; set; }
        public string lockTime { get; set; }
        public Nullable<int> winpercent { get; set; }
        public Nullable<long> BankGold { get; set; }
        public Nullable<int> vlevel { get; set; }
        public Nullable<int> givecount { get; set; }
        public Nullable<long> MaxLose { get; set; }
        public Nullable<long> MaxWin { get; set; }
        public Nullable<long> MaxGold { get; set; }
        public Nullable<long> TotalGold { get; set; }
        public Nullable<int> showid { get; set; }
        public Nullable<float> lat { get; set; }
        public Nullable<float> lng { get; set; }
        public string UserPassword { get; set; }
        public Nullable<int> IsTp { get; set; }
        public Nullable<int> lv { get; set; }
        public Nullable<int> IsJdb { get; set; }
        public Nullable<long> UpTotalAmount { get; set; }
        public Nullable<int> RobotGameid { get; set; }
        public string clublist { get; set; }
    }
}
