//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tusergamehand
    {
        public string Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> clubid { get; set; }
        public Nullable<decimal> pos1Count { get; set; }
        public Nullable<decimal> pos2Count { get; set; }
        public Nullable<decimal> pos5Count { get; set; }
        public Nullable<decimal> pos10Count { get; set; }
        public Nullable<decimal> pos20Count { get; set; }
        public Nullable<decimal> pos50Count { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> gameWinCount { get; set; }
        public Nullable<int> gameLostCount { get; set; }
        public Nullable<int> gameDrawCount { get; set; }
        public Nullable<int> FillingCount { get; set; }
        public Nullable<int> dealCardCount { get; set; }
        public Nullable<int> todayCardCount { get; set; }
        public Nullable<System.DateTime> lastdealtime { get; set; }
        public Nullable<int> tablenum { get; set; }
    }
}
