//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tuseragent2019
    {
        public int UserID { get; set; }
        public Nullable<int> Lv { get; set; }
        public Nullable<int> FUserID { get; set; }
        public Nullable<double> GoldHistoryCommission { get; set; }
        public Nullable<double> GoldCommission { get; set; }
        public string QRPath { get; set; }
        public string Code { get; set; }
        public string HtmlUrl { get; set; }
        public Nullable<System.DateTime> lastdealtime { get; set; }
        public Nullable<long> watergoldadd { get; set; }
        public Nullable<long> watergoldreduce { get; set; }
        public Nullable<long> childwater { get; set; }
        public string ChildAgents { get; set; }
        public Nullable<int> TopUserID { get; set; }
        public Nullable<int> dealCardCount { get; set; }
        public Nullable<int> SecondUserID { get; set; }
        public Nullable<int> todayCardCount { get; set; }
        public Nullable<long> TopUserGoldCommission { get; set; }
        public string rate3 { get; set; }
        public Nullable<double> GoldC_pot { get; set; }
        public Nullable<int> gameWinCount { get; set; }
        public Nullable<int> gameLostCount { get; set; }
        public Nullable<int> gameDrawCount { get; set; }
        public string WhirlCount { get; set; }
        public string TexasCount { get; set; }
    }
}
