//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvisitlimit
    {
        public string ipport { get; set; }
        public string dateRecord { get; set; }
        public string unitRcord { get; set; }
        public Nullable<int> dateMaxLimit { get; set; }
        public Nullable<int> unitMaxLimit { get; set; }
    }
}
