//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class userrole
    {
        public int RoleId { get; set; }
        public int UserId { get; set; }
        public string RoleName { get; set; }
        public string HeadImg { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<int> LvNum { get; set; }
        public Nullable<int> ExperienceNum { get; set; }
        public Nullable<int> LifeNum { get; set; }
        public Nullable<int> LifeMaxNum { get; set; }
        public Nullable<int> pos_x { get; set; }
        public Nullable<int> pos_y { get; set; }
        public Nullable<int> pos_z { get; set; }
        public string scene_name { get; set; }
    }
}
