//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy2018_Sys_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_manager_role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dt_manager_role()
        {
            this.dt_manager_role_value = new HashSet<dt_manager_role_value>();
        }
    
        public int id { get; set; }
        public string role_name { get; set; }
        public Nullable<int> role_type { get; set; }
        public Nullable<int> is_sys { get; set; }
        public Nullable<int> role_value { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dt_manager_role_value> dt_manager_role_value { get; set; }
    }
}
